### PR TITLE
Cleaned up README

### PR DESCRIPTION
**Pull request by 0xcaff**
I cleaned up the readme and converted it to markdown.

### CODE REVIEW

**Comment by WinterMute** [comment]
Don't rename the file - README is a standard name on several platforms & it doesn't need the .md extension for github to render the markdown

**Comment by 0xcaff** [comment]
I just tested it and the `*.md` extension is needed to render the file as markdown. [Reference.](http://stackoverflow.com/questions/8655937/github-readme-and-readme-md#answer-8655950) What platforms are rigidly only searching for `README`s instead of anything that matches the Regexp `/^readme.*$/i`?

**Comment by 0xcaff** [comment]
CC: @artart78 @libcg

**Comment by libcg** [comment]
I'm okay with this pull request. @WinterMute

**Comment by artart78** [comment]
Renaming the README file doesn't seem to be a big issue, and many projects do it. I think it can be merged safely.

**Pull request merged**
